# -*- coding: utf-8 -*-
"""CAPSTONE USA.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gpK9YOYMyz4PkJl0OZoOk9RNXzkx0zuD
"""

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib notebook

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import re

#needed for text processing and analytics
import nltk
import nltk.stem

from nltk.tokenize import word_tokenize, sent_tokenize, PunktSentenceTokenizer
from nltk import pos_tag, sent_tokenize, word_tokenize, BigramAssocMeasures,\
    BigramCollocationFinder, TrigramAssocMeasures, TrigramCollocationFinder
from nltk.corpus import stopwords
from string import punctuation

#visualization
from plotly import tools
import plotly as py
from plotly.offline import init_notebook_mode, iplot
init_notebook_mode(connected=True)
import plotly.graph_objs as go

import sys
import warnings

if not sys.warnoptions:
    warnings.simplefilter("ignore")


#to plot inside the document
# %matplotlib inline
import matplotlib.pyplot as plt

# Any results you write to the current directory are saved as output.

#load the dataset
debates = pd.read_csv("/content/drive/MyDrive/SET A/un-general-debates.csv")

debates

debates.head()

debates.tail()

debates = debates.loc[debates['country'] == 'USA']

"""**Pre-Processing**

Text Processing will be done in two levels:-

*   Extracting meta text data and creating new features.
*   Process the text and create new features with tokens, cleaned text and stems.


"""

# create features from meta text data
debates['char_count'] = debates['text'].str.len()
debates['words'] = debates['text'].str.split(' ')
debates['sentences'] = debates['text'].str.split('.')
debates['word_count'] = debates['words'].str.len()
debates['sentence_count'] = debates['sentences'].str.len()
debates['word_length'] = debates['char_count'] / debates['word_count']
debates['sentence_length'] = debates['word_count'] / debates['sentence_count']

"""




*   Tokenize - Tokenization is the task of chopping it up into pieces, called tokens , perhaps at the same time throwing away certain characters, such as punctuation.

*   Clean - Stop Word Removal is the process of removing the stop words. A stop word is a commonly used word (such as “the”, “a”, “an”, “in”) that a search engine has been programmed to ignore, both when indexing entries for searching and when retrieving them as the result of a search queries.

*   Stemmer - Stemming is the process of reducing inflected (or sometimes derived) words to their word stem, base or root form—generally a written word form.


*   Lemmatizer - Lemmatization usually refers to doing things properly with the use of a vocabulary and morphological analysis of words, normally aiming to remove inflectional endings only and to return the base or dictionary form of a word, which is known as the lemma .

"""

import re
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from string import punctuation

# Sample data creation (assuming you have a DataFrame named 'debates')
# debates = pd.DataFrame({'text': ["Your sample text here"], 'year': [2023]})

# Ensure NLTK resources are downloaded
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

# Text processing
debates['text'] = debates['text'].str.lower().map(lambda x: re.sub('\W+', ' ', x))
debates['text'] = debates['text'].str.lower().map(lambda x: re.sub('united nations', 'united_nations', x))
debates['token'] = debates['text'].apply(word_tokenize)

# Stop words and additional tokens to remove
stop_words = set(stopwords.words('english'))
stop_words.update(["'s", "'", "-", "’"])

# Removing stop words and punctuation
debates['clean'] = debates['token'].apply(lambda x: [w for w in x if w not in stop_words and w not in punctuation])

# Function to get lemma of a word
from nltk.corpus import wordnet as wn

def get_lemma(word):
    lemma = wn.morphy(word)
    return word if lemma is None else lemma

# Stemming and lemmatizing
debates['stems'] = debates['clean'].apply(lambda x: [get_lemma(token) for token in x])

# Sorting the DataFrame by year
debates = debates.sort_values('year')

"""This code generates violin plots for the distributions of four meta text features in the 'debates' dataset: word count, average word length,sentence count, and average sentence length per speech. The plots display the spread and density of these features, along with the means, to visualize their variability across speeches.






"""

# Look at the meta text features' distributions
plt.figure(figsize=(16, 8))
fig, axes = plt.subplots(nrows=2, ncols=2, figsize=(10, 10))
all_data = [debates]

axes[0, 0].violinplot(debates['word_count'], showmeans=True, showmedians=False)
axes[0, 0].set_title('Word Count per Speech')

axes[0, 1].violinplot(debates['word_length'], showmeans=True, showmedians=False)
axes[0, 1].set_title('Avg. Word Length per Speech')

axes[1, 0].violinplot(debates['sentence_count'], showmeans=True, showmedians=False)
axes[1, 0].set_title('Sentence Count per Speech')

axes[1, 1].violinplot(debates['sentence_length'], showmeans=True, showmedians=False)
axes[1, 1].set_title('Avg. Sentence Length per Speech')

# add x-tick labels
plt.setp(axes, xticks=[y+1 for y in range(len(all_data))], xticklabels=['Frequency'])
fig.subplots_adjust(wspace=.5, hspace=.5)
plt.show()

"""This code creates and displays a Plotly interactive line chart that visualizes the trends of character count, word count, and sentence count over the years in the 'debates' dataset. Each line is filled to the next line to emphasize the area under the curves, providing a clear visual comparison of these text features across different years."""

import plotly.graph_objects as go
from plotly.offline import init_notebook_mode, iplot
import pandas as pd

# Assuming 'debates' is a pandas DataFrame with columns 'year', 'char_count', 'word_count', 'sentence_count'

trace1 = go.Scatter(
    x=debates['year'],
    y=debates['char_count'],
    fill='tonexty',
    name='Character Count'
)
trace2 = go.Scatter(
    x=debates['year'],
    y=debates['word_count'],
    fill='tonexty',
    name='Word Count'
)
trace3 = go.Scatter(
    x=debates['year'],
    y=debates['sentence_count'],
    fill='tonexty',
    name='Sentence Count'
)

data = [trace1, trace2, trace3]

# Initialize the notebook mode
init_notebook_mode(connected=True)

# Create the figure and display the plot
fig = go.Figure(data=data)
fig.show(renderer="colab")

"""This code groups the 'debates' dataset by 'session' and calculates the mean 'year' and the sum of 'clean' (possibly representing cleaned text or word count) for each session. The result is a DataFrame where each row corresponds to a session, showing the average year and the total cleaned text for that session."""

all_per_year = debates.groupby('session').agg({'year': 'mean', 'clean': 'sum'})

"""This code generates a word cloud of the most frequently used words in the 'clean' text data from the 'all_per_year' DataFrame, excluding common English stopwords. The word cloud visually represents the frequency of words used in the US UN Debate sessions, with more frequently used words appearing larger."""

import nltk
from wordcloud import WordCloud, STOPWORDS

words = []
for i, row in all_per_year.iterrows():
    words = nltk.FreqDist(row['clean'])

words = nltk.FreqDist(words)
stopwords = nltk.corpus.stopwords.words('english')
words_except_stop_dist = nltk.FreqDist(w for w in words if w not in stopwords)
wordcloud = WordCloud(stopwords=STOPWORDS,background_color='white').generate(" ".join(words_except_stop_dist))
plt.imshow(wordcloud,interpolation='bilinear')
fig=plt.gcf()
fig.set_size_inches(16,8)
plt.title("Most used words by the US at UN Debate sessions")
plt.axis('off')
plt.show()

"""This code defines functions to generate and replace bigrams and trigrams in a text, enhancing word cloud visualizations by combining common word pairs and triplets. It also includes functions to process text by tokenizing, lemmatizing, and removing stopwords before applying bigram and trigram transformations."""

#from https://www.kaggle.com/peterwittek/wordclouds-of-titles-and-abstracts-with-n-grams
#definations for Bi-Trigrams for Wordcloud viz
def get_bitrigrams(full_text, threshold=30):
    if isinstance(full_text, str):
        text = full_text
    else:
        text = " ".join(full_text)
    bigram_measures = BigramAssocMeasures()
    trigram_measures = TrigramAssocMeasures()
    finder = BigramCollocationFinder.from_words(text.split())
    finder.apply_freq_filter(3)
    bigrams = {" ".join(words): "_".join(words)
               for words in finder.above_score(bigram_measures.likelihood_ratio, threshold)}
    finder = TrigramCollocationFinder.from_words(text.split())
    finder.apply_freq_filter(3)
    trigrams = {" ".join(words): "_".join(words)
                for words in finder.above_score(trigram_measures.likelihood_ratio, threshold)}
    return bigrams, trigrams


def replace_bitrigrams(text, bigrams, trigrams):
    if isinstance(text, str):
        texts = [text]
    else:
        texts = text
    new_texts = []
    for t in texts:
        t_new = t
        for k, v in trigrams.items():
            t_new = t_new.replace(k, v)
        for k, v in bigrams.items():
            t_new = t_new.replace(" " + k + " ", " " + v + " ")
        new_texts.append(t_new)
    if len(new_texts) == 1:
        return new_texts[0]
    else:
        return new_texts

def process_text(text, lemmatizer, translate_table, stopwords):
    processed_text = ""
    for sentence in sent_tokenize(text):
        tagged_sentence = pos_tag(word_tokenize(sentence.translate(translate_table)))
        for word, tag in tagged_sentence:
            word = word.lower()
            if word not in stopwords:
                if tag[0] != 'V':
                    processed_text += lemmatizer.lemmatize(word) + " "
    return processed_text


def get_all_processed_texts(texts, lemmatizer, translate_table, stopwords):
    processed_texts = []
    for index, doc in enumerate(texts):
        processed_texts.append(process_text(doc, wordnet_lemmatizer, translate_table, stop))
    bigrams, trigrams = get_bitrigrams(processed_texts)
    very_processed_texts = replace_bitrigrams(processed_texts, bigrams, trigrams)
    return " ".join(very_processed_texts)

"""This code processes text data from US UN Debate sessions by tokenizing, lemmatizing, and removing stopwords, then generates and replaces bigrams to enhance the text. Finally, it creates and displays a word cloud highlighting the most frequently used bigrams in these debates."""

import nltk
from nltk.collocations import BigramCollocationFinder, BigramAssocMeasures
from nltk import WordNetLemmatizer
from wordcloud import WordCloud, STOPWORDS
from nltk.corpus import stopwords
import string
import matplotlib.pyplot as plt

# Download necessary NLTK resources
nltk.download('averaged_perceptron_tagger')
nltk.download('stopwords')
nltk.download('wordnet')

wordnet_lemmatizer = WordNetLemmatizer()
stop = set(stopwords.words('english'))
translate_table = str.maketrans(string.punctuation, ' '*len(string.punctuation))

def process_text(doc, lemmatizer, translate_table, stopwords):
    tokens = doc.lower().translate(translate_table).split()
    return ' '.join([lemmatizer.lemmatize(word) for word in tokens if word not in stopwords])

def get_bitrigrams(processed_texts):
    bigram_measures = BigramAssocMeasures()
    finder = BigramCollocationFinder.from_documents([text.split() for text in processed_texts])
    finder.apply_freq_filter(3)  # Example filter, adjust as needed
    bigrams = {' '.join(bigram): '_'.join(bigram) for bigram, score in finder.score_ngrams(bigram_measures.pmi)}
    return bigrams, {}  # Empty trigram dict for simplicity

def use_ngrams_only(texts, lemmatizer, translate_table, stopwords):
    processed_texts = []
    for index, doc in enumerate(texts):
        processed_texts.append(process_text(doc, lemmatizer, translate_table, stopwords))
    bigrams, trigrams = get_bitrigrams(processed_texts)
    indexed_texts = []
    for doc in processed_texts:
        current_doc = []
        for k, v in trigrams.items():
            c = doc.count(k)
            if c > 0:
                current_doc += [v] * c
                doc = doc.replace(k, v)
        for k, v in bigrams.items():
            current_doc += [v] * doc.count(" " + k + " ")
        indexed_texts.append(" ".join(current_doc))
    return " ".join(indexed_texts)

wordcloud = WordCloud(stopwords=STOPWORDS, background_color="white").\
    generate(use_ngrams_only(debates['text'], wordnet_lemmatizer, translate_table, stop))
plt.figure(figsize=(16, 8))
plt.imshow(wordcloud, interpolation='bilinear')
plt.title("Most used Bi-grams by the US at UN Debate sessions")
plt.axis("off")
plt.show()

"""**Finding Word Frequencies and Related Visualization**

In this section, first we find the frequency of different words used by the delegation in their speeches. Later, visualize them over to find particular patterns during the speeches over the years. Here, we take in consideration the stemmed words only because it makes more sense. For example, a stemmed word like terror make more sense than terrorist, terrorism, terrorising.
"""

#creating frequency of words
freqs = {}
for i, speech in debates.iterrows():
    year = speech['year']
    for token in speech['stems']:
        if token not in freqs:
            freqs[token] = {"total_freq":1, year:1}
        else:
            freqs[token]["total_freq"] += 1
            if not freqs[token].get(year):
                freqs[token][year] = 1
            else:
                freqs[token][year] += 1

#create a dataframe to store the words and their frequencies
freqs_df = pd.DataFrame.from_dict(freqs, orient='index')
freqs_df['word'] = freqs_df.index
new_cols = ["total_freq", "word"] + sorted(freqs_df.columns.tolist()[1:-1])
freqs_df = freqs_df[new_cols]
freqs_df = freqs_df.sort_values('total_freq', ascending=False)
freqs_df = freqs_df.fillna(0)
freqs_df.head()

# Create a scatter plot to visualize the top 100 words over the years
trace = go.Scatter(
    x=freqs_df.iloc[0:100]['word'],  # x-axis: words
    y=freqs_df.iloc[0:100]['total_freq'],  # y-axis: total frequency of words
    mode='lines+markers',
    name='Word Frequency'
)

# Define the layout for the plot
layout = dict(
    title='Frequency of Words Used Over Years',
    xaxis=dict(title='Word'),
    yaxis=dict(title='Count')
)

# Create the figure and display the plot
fig = go.Figure(data=[trace], layout=layout)
fig.show(renderer="colab", filename='basic-line')

"""Here we try to visualize the most frequent words ( top five ) every year from 1971 to 2016."""

import plotly.graph_objects as go

# Define the range of years
RANGE = (1971, 2016)

# Create a scatter plot to visualize the top words over the years
fig = go.Figure()

for year in range(*RANGE):
    top5 = freqs_df.nlargest(5, columns=(year))  # Ensure the year is a string

    fig.add_trace(go.Scatter(
        x=[year]*len(top5),
        y=top5[(year)],
        mode='markers+text',
        text=top5['word'],
        textposition='top center',
        marker=dict(size=10),
        name=str(year)
    ))

# Update layout to make it visually appealing
fig.update_layout(
    title='Top 5 Words Used Over the Years',
    xaxis=dict(title='Year', tickmode='linear', tick0=RANGE[0], dtick=1, range=RANGE),
    yaxis=dict(title='Frequency'),
    showlegend=False,
    hovermode='closest',
    width=1200,
    height=600
)

# Display the plot
fig.show(renderer="colab")

"""The above plot is a scatter plots.

**Topic Extraction using Gensim**

Gensim is a robust open-source vector space modeling and topic modeling toolkit implemented in Python. It uses NumPy, SciPy and optionally Cython for performance. Here, we use Gensim to get the topics in the text.
"""

text_data = list(debates['clean'])

from gensim import corpora
dictionary = corpora.Dictionary(text_data)
corpus = [dictionary.doc2bow(text) for text in text_data]
#import pickle
#pickle.dump(corpus, open('corpus.pkl', 'wb'))
#dictionary.save('dictionary.gensim')

import gensim
ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = 10, id2word=dictionary, passes=15)
ldamodel.save('model10.gensim')
topics = ldamodel.print_topics(num_words=10)
for topic in topics:
    print(topic)

"""I have commented the code the under mentioned. pyLDAvis changes the HTML too much and results in a weird view of the Kernel. While running locally one can uncomment an d visualize the topics, its very interesting."""

!pip install pyLDAvis

import pyLDAvis.gensim
lda10 = gensim.models.ldamodel.LdaModel.load('model10.gensim')
lda_display10 = pyLDAvis.gensim.prepare(lda10, corpus, dictionary, sort_topics=False)
pyLDAvis.display(lda_display10)

print(text_data)

from gensim import corpora, models
dictionary = corpora.Dictionary(text_data)
corpus = [dictionary.doc2bow(text) for text in text_data]
ldamodel = models.ldamodel.LdaModel(corpus, id2word=dictionary,
                                    num_topics=10, passes=5, minimum_probability=0)

hm = np.array([[y for (x,y) in ldamodel[corpus[i]]] for i in range(len(corpus))], dtype=object)
print(hm)

freqs_df.iloc[0:5, 1:47].transpose().iloc[1:].plot(title="Most common words",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['peace', 'war', 'security', 'cold', 'conflict', 'aggression'])].iloc[:, 1:47].transpose().iloc[1:].plot(title = "War and Peace",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['economy', 'wealth', 'crisis', 'growth', 'inflation', 'trade', 'poverty', 'rich', 'income'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="Economy",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['people', 'refugee', 'humanitarian', 'freedom', 'right'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="People",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['democracy', 'republic', 'dictator', 'sovereign', 'politics'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="Politics",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['violence', 'kill', 'death'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="Violence",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['environment', 'sustain', 'green', 'energy', 'ecology', 'warm', 'temperature', 'pollution', 'planet'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="Environment",figsize=(16,8))

freqs_df[freqs_df['word'].isin(['terror','terrorism','terrorist'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="Terrorism",figsize=(16,8))

"""**Countries mentioned by USA and related Visualization**

In this section, we try to find the countries mentioned by USA in the speeches over the years. First we obtain the list of countries from an external package and later we find the mention of the countries in the text. We create a new dataframe to store the frequencies of countries mentioned by India.
"""

!pip install pycountry

import pycountry
list_of_countries = []
for i in range(len(pycountry.countries)):
    x = list(pycountry.countries)[i]
    list_of_countries.append(x.name.lower())
print(list_of_countries)

debates['countries_mentioned'] = debates['token'].apply(lambda token: {x:token.count(x) for x in token if x in list_of_countries})

country_mentions = pd.concat([debates[["year"]],
                              debates['countries_mentioned'].apply(pd.Series)], axis=1).dropna(axis=1, how='all')
country_mentions = country_mentions.reset_index()
del country_mentions['index']
country_mentions.head()

country_mentions = country_mentions.transpose()
country_mentions["total_mention"] = country_mentions.sum(axis=1)

country_mentions = country_mentions.sort_values('total_mention', ascending=False)
country_mentions = country_mentions.transpose()
country_mentions = country_mentions.drop(country_mentions.index[len(country_mentions)-1])
country_mentions['year'] =country_mentions['year'].apply(np.int64)
country_mentions = country_mentions.sort_values('year')
country_mentions = country_mentions.fillna(0)
country_mentions.head()

country_mentions.plot(x="year", y=["iraq","israel","afghanistan","china","lebanon","cyprus","namibia","ukraine","egypt"],figsize=(16,8))
plt.show()

country_mentions = country_mentions.rename_axis(None)
country_mentions = country_mentions.set_index('year').T
country_mentions['country'] = country_mentions.index

import plotly.express as px
import pandas as pd

# Assuming 'country_mentions' is your DataFrame with country mentions by year
# Replace this with the actual DataFrame creation/loading code if necessary

# Flatten the data for easier plotting with Plotly
data = []
for year in range(1971, 2016):
    top5 = country_mentions.nlargest(5, columns=year)
    for _, row in top5.iterrows():
        data.append({'Year': year, 'Country': row['country'], 'Mentions': row[year]})

# Convert to DataFrame
plot_df = pd.DataFrame(data)

# Create scatter plot with Plotly
fig = px.scatter(plot_df, x='Year', y='Mentions', color='Country',
                 hover_data={'Year': True, 'Country': True, 'Mentions': True},
                 title="Top 5 Country Mentions by Year")

# Show the plot
fig.show(renderer="colab")

"""Sentiment Analysis of Speech In this section we try analyze the sentiment of speeches given by Indian Delegation at the United Nations debates. We make use of a simple Sentiment Analyzer named Vader from NLTK.


"""

from nltk.sentiment.vader import SentimentIntensityAnalyzer

def analize_sentiment(text):
    sid = SentimentIntensityAnalyzer()
    ss = sid.polarity_scores(text)
    if ss["compound"] == 0.0:
        sent = 0.0
    elif ss["compound"] > 0.0:
        sent = 1.0
    else:
        sent = -1.0
    return ss["compound"]

def analize_polarity(text):
    sid = SentimentIntensityAnalyzer()
    ss = sid.polarity_scores(text)
    if ss["compound"] == 0.0:
        sent = "Neutral"
    elif ss["compound"] > 0.0:
        sent = "Postive"
    else:
        sent = "Negative"
    return sent

import nltk
from nltk.sentiment.vader import SentimentIntensityAnalyzer
import numpy as np
import pandas as pd

# Download the VADER lexicon
nltk.download('vader_lexicon')

# Initialize the VADER sentiment analyzer
sid = SentimentIntensityAnalyzer()

# Define the sentiment analysis function
def analize_sentiment(text):
    return sid.polarity_scores(text)['compound']

# Define the polarity analysis function if different from sentiment
def analize_polarity(text):
    scores = sid.polarity_scores(text)
    return scores['pos'] - scores['neg']

# Assuming 'debates' is your DataFrame
debates['sentiment'] = np.array([analize_sentiment(text) for text in debates['text']])
debates['polarity'] = np.array([analize_polarity(text) for text in debates['text']])
debates.head()

import plotly.graph_objects as go
from plotly.offline import iplot

data = [go.Bar(
           x=debates['year'],
           y=debates['sentiment']
    )]

fig = go.Figure(data=data)
fig.update_layout(title='Sentiment Analysis Over Years',
                  xaxis_title='Year',
                  yaxis_title='Sentiment Score')

fig.show(renderer="colab")

deb_values = debates.groupby(['polarity'],axis=0).count()
deb_values.head()

label = ['Negative','Postive']
values = deb_values['text']
fig = go.Figure(data=[go.Pie(labels=label, values=values)])
fig.update_layout(title='Polarity of Speeches by USA')

fig.show(renderer="colab")

"""**Mention of US by Other countries**"""

data= pd.read_csv("/content/drive/MyDrive/SET A/un-general-debates.csv")
data.head()

#create feature with text processing
data['text'] = data['text'].str.lower().map(lambda x: re.sub('\W+',' ', x))
data['token'] = data['text'].apply(word_tokenize)

data['usa_mentioned'] = data.text.str.count('united states')
data = data[data.country != 'USA']
data.head()

countries = dict((k, v.lower()) for k,v in {
    'AFG': 'Afghanistan',
    'ALA': 'Aland Islands',
    'ALB': 'Albania',
    'DZA': 'Algeria',
    'ASM': 'American Samoa',
    'AND': 'Andorra',
    'AGO': 'Angola',
    'AIA': 'Anguilla',
    'ATA': 'Antarctica',
    'ATG': 'Antigua and Barbuda',
    'ARG': 'Argentina',
    'ARM': 'Armenia',
    'ABW': 'Aruba',
    'AUS': 'Australia',
    'AUT': 'Austria',
    'AZE': 'Azerbaijan',
    'BHS': 'Bahamas',
    'BHR': 'Bahrain',
    'BGD': 'Bangladesh',
    'BRB': 'Barbados',
    'BLR': 'Belarus',
    'BEL': 'Belgium',
    'BLZ': 'Belize',
    'BEN': 'Benin',
    'BMU': 'Bermuda',
    'BTN': 'Bhutan',
    'BOL': 'Bolivia',
    'BIH': 'Bosnia and Herzegovina',
    'BWA': 'Botswana',
    'BVT': 'Bouvet Island',
    'BRA': 'Brazil',
    'VGB': 'Virgin Islands',
    'IOT': 'British Indian Ocean Territory',
    'BRN': 'Brunei',
    'BGR': 'Bulgaria',
    'BFA': 'Burkina Faso',
    'BDI': 'Burundi',
    'KHM': 'Cambodia',
    'CMR': 'Cameroon',
    'CAN': 'Canada',
    'CPV': 'Cape Verde',
    'CYM': 'Cayman Islands',
    'CAF': 'Central Africa',
    'TCD': 'Chad',
    'CHL': 'Chile',
    'CHN': 'China',
    'HKG': 'Hong Kong',
    'MAC': 'Macao',
    'CXR': 'Christmas Island',
    'CCK': 'Cocos Islands',
    'COL': 'Colombia',
    'COM': 'Comoros',
    'COG': 'Congo',
    'COD': 'Democratic Republic of Congo',
    'COK': 'Cook Islands',
    'CRI': 'Costa Rica',
    'CIV': "Cote d'Ivoire",
    'HRV': 'Croatia',
    'CUB': 'Cuba',
    'CYP': 'Cyprus',
    'CZE': 'Czech Republic',
    'DNK': 'Denmark',
    'DJI': 'Djibouti',
    'DMA': 'Dominica',
    'DOM': 'Dominican Republic',
    'ECU': 'Ecuador',
    'EGY': 'Egypt',
    'SLV': 'El Salvador',
    'GNQ': 'Equatorial Guinea',
    'ERI': 'Eritrea',
    'EST': 'Estonia',
    'ETH': 'Ethiopia',
    'FLK': 'Falkland',
    'FRO': 'Faroe',
    'FJI': 'Fiji',
    'FIN': 'Finland',
    'FRA': 'France',
    'GUF': 'French Guiana',
    'PYF': 'French Polynesia',
    'ATF': 'French Southern Territories',
    'GAB': 'Gabon',
    'GMB': 'Gambia',
    'GEO': 'Georgia',
    'DEU': 'Germany',
    'GHA': 'Ghana',
    'GIB': 'Gibraltar',
    'GRC': 'Greece',
    'GRL': 'Greenland',
    'GRD': 'Grenada',
    'GLP': 'Guadeloupe',
    'GUM': 'Guam',
    'GTM': 'Guatemala',
    'GGY': 'Guernsey',
    'GIN': 'Guinea',
    'GNB': 'Guinea-Bissau',
    'GUY': 'Guyana',
    'HTI': 'Haiti',
    'HMD': 'Heard and Mcdonald Islands',
    'VAT': 'Vatican',
    'HND': 'Honduras',
    'HUN': 'Hungary',
    'ISL': 'Iceland',
    'IND': 'India',
    'IDN': 'Indonesia',
    'IRN': 'Iran',
    'IRQ': 'Iraq',
    'IRL': 'Ireland',
    'IMN': 'Isle of Man',
    'ISR': 'Israel',
    'ITA': 'Italy',
    'JAM': 'Jamaica',
    'JPN': 'Japan',
    'JEY': 'Jersey',
    'JOR': 'Jordan',
    'KAZ': 'Kazakhstan',
    'KEN': 'Kenya',
    'KIR': 'Kiribati',
    'PRK': 'North Korea',
    'KOR': 'South Korea',
    'KWT': 'Kuwait',
    'KGZ': 'Kyrgyzstan',
    'LAO': 'Lao',
    'LVA': 'Latvia',
    'LBN': 'Lebanon',
    'LSO': 'Lesotho',
    'LBR': 'Liberia',
    'LBY': 'Libya',
    'LIE': 'Liechtenstein',
    'LTU': 'Lithuania',
    'LUX': 'Luxembourg',
    'MKD': 'Macedonia',
    'MDG': 'Madagascar',
    'MWI': 'Malawi',
    'MYS': 'Malaysia',
    'MDV': 'Maldives',
    'MLI': 'Mali',
    'MLT': 'Malta',
    'MHL': 'Marshall Islands',
    'MTQ': 'Martinique',
    'MRT': 'Mauritania',
    'MUS': 'Mauritius',
    'MYT': 'Mayotte',
    'MEX': 'Mexico',
    'FSM': 'Micronesia',
    'MDA': 'Moldova',
    'MCO': 'Monaco',
    'MNG': 'Mongolia',
    'MNE': 'Montenegro',
    'MSR': 'Montserrat',
    'MAR': 'Morocco',
    'MOZ': 'Mozambique',
    'MMR': 'Myanmar',
    'NAM': 'Namibia',
    'NRU': 'Nauru',
    'NPL': 'Nepal',
    'NLD': 'Netherlands',
    'ANT': 'Netherlands Antilles',
    'NCL': 'New Caledonia',
    'NZL': 'New Zealand',
    'NIC': 'Nicaragua',
    'NER': 'Niger',
    'NGA': 'Nigeria',
    'NIU': 'Niue',
    'NFK': 'Norfolk Island',
    'MNP': 'Northern Mariana Islands',
    'NOR': 'Norway',
    'OMN': 'Oman',
    'PAK': 'Pakistan',
    'PLW': 'Palau',
    'PSE': 'Palestine',
    'PAN': 'Panama',
    'PNG': 'Papua New Guinea',
    'PRY': 'Paraguay',
    'PER': 'Peru',
    'PHL': 'Philippines',
    'PCN': 'Pitcairn',
    'POL': 'Poland',
    'PRT': 'Portugal',
    'PRI': 'Puerto Rico',
    'QAT': 'Qatar',
    'REU': 'Reunion',
    'ROU': 'Romania',
    'RUS': 'Russia',
    'RWA': 'Rwanda',
    'BLM': 'Saint-Barthelemy',
    'SHN': 'Saint Helena',
    'KNA': 'Saint Kitts',
    'LCA': 'Saint Lucia',
    'MAF': 'Saint-Martin',
    'SPM': 'Saint Pierre and Miquelon',
    'VCT': 'Saint Vincent and Grenadines',
    'WSM': 'Samoa',
    'SMR': 'San Marino',
    'STP': 'Sao Tome and Principe',
    'SAU': 'Saudi Arabia',
    'SEN': 'Senegal',
    'SRB': 'Serbia',
    'SYC': 'Seychelles',
    'SLE': 'Sierra Leone',
    'SGP': 'Singapore',
    'SVK': 'Slovakia',
    'SVN': 'Slovenia',
    'SLB': 'Solomon Islands',
    'SOM': 'Somalia',
    'ZAF': 'South Africa',
    'SGS': 'South Georgia and the South Sandwich Islands',
    'SSD': 'South Sudan',
    'ESP': 'Spain',
    'LKA': 'Sri Lanka',
    'SDN': 'Sudan',
    'SUR': 'Suriname',
    'SJM': 'Svalbard',
    'SWZ': 'Swaziland',
    'SWE': 'Sweden',
    'CHE': 'Switzerland',
    'SYR': 'Syria',
    'TWN': 'Taiwan',
    'TJK': 'Tajikistan',
    'TZA': 'Tanzania',
    'THA': 'Thailand',
    'TLS': 'Timor',
    'TGO': 'Togo',
    'TKL': 'Tokelau',
    'TON': 'Tonga',
    'TTO': 'Trinidad',
    'TUN': 'Tunisia',
    'TUR': 'Turkey',
    'TKM': 'Turkmenistan',
    'TCA': 'Turks and Caicos Islands',
    'TUV': 'Tuvalu',
    'UGA': 'Uganda',
    'UKR': 'Ukraine',
    'ARE': 'United Arab Emirates',
    'GBR': 'United Kingdom',
    'USA': 'United States',
    'UMI': 'US Minor Outlying Islands',
    'URY': 'Uruguay',
    'UZB': 'Uzbekistan',
    'VUT': 'Vanuatu',
    'VEN': 'Venezuela',
    'VNM': 'Viet Nam',
    'VIR': 'Virgin Islands',
    'WLF': 'Wallis and Futuna',
    'ESH': 'Western Sahara',
    'YEM': 'Yemen',
    'ZMB': 'Zambia',
    'ZWE': 'Zimbabwe'
}.items())

data['country'] = data['country'].map(countries)
data.head()

# Group by 'country' and sum the columns starting from the third column
data_mention = data.groupby("country")[data.columns[2:]].sum()

# Sort by 'usa_mentioned' column in descending order
data_mention = data_mention.sort_values('usa_mentioned', ascending=False)

# Keep only 'country' and 'usa_mentioned' columns, and select the top 11 rows
data_mention = data_mention[['usa_mentioned']].head(11)

# Display the resulting DataFrame
data_mention

countries_which_mention_usa = data_mention.index.values.tolist()

countries_which_mention_usa

data = data.loc[data['country'].isin(countries_which_mention_usa)]
data_future = data
data.head()

data=data[['year','country','usa_mentioned']]
data.head()

data = data.pivot(index='year', columns='country', values='usa_mentioned')
data.head()

data = data.fillna(0)
data.head()

data = data.reset_index()
data.head()

data.set_index(data['year'])
data.head()

"""Let's visualize the countries which mentioned USA most times."""

data.plot(x="year", y=countries_which_mention_usa,figsize=(16,8))
plt.show()

"""What Cuba says about USA in UN ?"""

data_future = data_future.loc[data_future['country'] == 'cuba']
data_future.head()

"""Lets, select only the talks where Cuba mentioned "USA" more than 10 times,"""

data_future = data_future.loc[data_future['usa_mentioned'] >= 10]

"""Lets, see which were the most frequent words except "usa" in these speechs,"""

import nltk
from wordcloud import WordCloud, STOPWORDS

words = []
for i, row in data_future.iterrows():
    words = nltk.FreqDist(row['token'])

words = nltk.FreqDist(words)
stopwords = nltk.corpus.stopwords.words('english')
words_except_stop_dist = nltk.FreqDist(w for w in words if w not in stopwords)
wordcloud = WordCloud(stopwords=STOPWORDS,background_color='white').generate(" ".join(words_except_stop_dist))
plt.imshow(wordcloud,interpolation='bilinear')
fig=plt.gcf()
fig.set_size_inches(16,8)
plt.title("Most used words by Cuba at UN Debate sessions (where they mentioned USA more than 10 times)")
plt.axis('off')
plt.show()

#creating frequency of words
freqs = {}
for i, speech in data_future.iterrows():
    year = speech['year']
    for token in speech['token']:
        if token not in freqs:
            freqs[token] = {"total_freq":1, year:1}
        else:
            freqs[token]["total_freq"] += 1
            if not freqs[token].get(year):
                freqs[token][year] = 1
            else:
                freqs[token][year] += 1

data_future['sentiment'] = np.array([ analize_sentiment(text) for text in data_future['text'] ])
data_future['polarity'] = np.array([ analize_polarity(text) for text in data_future['text'] ])
data_future.head()

import plotly.graph_objects as go
from plotly.offline import iplot


data = [go.Bar(
           x=data_future['year'],
           y=data_future['sentiment']
    )]

fig = go.Figure(data=data)
fig.update_layout(title='Sentiment Analysis Over Years',
                  xaxis_title='Year',
                  yaxis_title='Sentiment Score')

fig.show(renderer="colab")

stop_words.add("united states")
stop_words.add("cuba")
data_future['clean'] = data_future['token'].apply(lambda x: [w for w in x if not w in stop_words and not w in punctuation])

data_future['stems'] = [[format(get_lemma(token)) for token in speech] for speech in data_future['clean']]

data_future.head()

#creating frequency of words
freqs = {}
for i, speech in data_future.iterrows():
    year = speech['year']
    for token in speech['stems']:
        if token not in freqs:
            freqs[token] = {"total_freq":1, year:1}
        else:
            freqs[token]["total_freq"] += 1
            if not freqs[token].get(year):
                freqs[token][year] = 1
            else:
                freqs[token][year] += 1

freqs_df = pd.DataFrame.from_dict(freqs, orient='index')
freqs_df['word'] = freqs_df.index
new_cols = ["total_freq", "word"] + sorted(freqs_df.columns.tolist()[1:-1])
freqs_df = freqs_df[new_cols]
freqs_df = freqs_df.sort_values('total_freq', ascending=False)
freqs_df = freqs_df.fillna(0)
freqs_df.head()

import plotly.graph_objects as go

# Assuming freqs_df is your DataFrame containing word frequencies
# and total frequencies over the years

# Assuming freqs_df is already defined correctly

# Plot to visualize top 100 words over the years
trace = go.Scatter(
    x=freqs_df.iloc[0:100]['word'],
    y=freqs_df['total_freq']
)

layout = dict(
    title='Frequency of Words used over years by Cuba (USA Obsessed Speeches)',
    xaxis=dict(title='Word'),
    yaxis=dict(title='Count')
)

fig = go.Figure(data=[trace], layout=layout)

# Display the plot using fig.show()
fig.show(renderer="colab")

freqs_df[freqs_df['word'].isin(['international', 'war', 'effort', 'nuclear', 'general', 'sovereignty'])].iloc[:, 1:47].transpose().iloc[1:].plot(title="Word Frequency",figsize=(16,8))

text_data = list(data_future['clean'])

from gensim import corpora
dictionary = corpora.Dictionary(text_data)
corpus = [dictionary.doc2bow(text) for text in text_data]
import pickle
pickle.dump(corpus, open('corpus.pkl', 'wb'))
dictionary.save('dictionary.gensim')

ldamodel = gensim.models.ldamodel.LdaModel(corpus, num_topics = 10, id2word=dictionary, passes=15)
ldamodel.save('model10.gensim')
topics = ldamodel.print_topics(num_words=4)
for topic in topics:
    print(topic)

"""Here's the topics Cuba speaks about USA at UN"""

import pyLDAvis.gensim
lda10 = gensim.models.ldamodel.LdaModel.load('model10.gensim')
lda_display10 = pyLDAvis.gensim.prepare(lda10, corpus, dictionary, sort_topics=False)
pyLDAvis.display(lda_display10)

